spring.application.name=tienda-jmr-lmg-fgg-web

#BASE DE DATOS H2 EN MEMORIA
# mem:tienda crea la base de datos en RAM con ese nombre
#DATABASE_TO_LOWER=TRUE hace que los nombres de tablas sean en minúsculas
spring.datasource.url=jdbc:h2:mem:tienda;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=jl
spring.datasource.password=

# --- COMPORTAMIENTO DE HIBERNATE ---
# update: Hibernate crea las tablas si no existen y las actualiza si cambian
#en producción se usaría "validate" o "none"
spring.jpa.hibernate.ddl-auto=update

# Muestra el SQL que genera Hibernate en la consola ahora es útil para aprender
spring.jpa.show-sql=true

# Formatea el SQL para que sea legible en el log
spring.jpa.properties.hibernate.format_sql=true

#Al iniciar always: ejecuta data.sql siempre al arrancar
spring.sql.init.mode=always

#Espera a que Hibernate cree las tablas antes de ejecutar data.sql
# sin esta línea, data.sql se ejecutaría antes de que existieran las tablas
spring.jpa.defer-datasource-initialization=true

# Permite ver la base de datos desde el navegador en /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console